import React, { useState } from 'react';
import { ArrowRight, ArrowLeft } from 'lucide-react';

const QUESTIONS = {
  physical: [
    { id: 'p1', text: 'Can your solution function during power outages or with intermittent / variable electricity — without relying on a constant grid connection?', hint: 'Think: solar cycles, battery buffers, episodic processing, graceful degradation.' },
    { id: 'p2', text: 'Does your solution work fully or meaningfully offline, without requiring constant internet connectivity?', hint: 'Think: offline-first architecture, local data caching, sync-when-connected design.' },
    { id: 'p3', text: 'Is your solution designed to run on low-specification or existing devices — not requiring the latest or most expensive hardware?', hint: 'Think: Android 8+, feature phones, shared tablets, 2GB RAM devices.' },
    { id: 'p4', text: 'Does your hardware (if any) support local repair, or can your software operate on hardware that is repairable and community-maintained?', hint: 'Think: modular components, available schematics, locally sourceable parts. If software-only, consider the devices it runs on.' },
    { id: 'p5', text: 'Does your solution minimize data transmission — compressing, batching, or only sending what is strictly necessary?', hint: 'Think: data is expensive. Every kilobyte has a cost to the user.' }
  ],
  spatial: [
    { id: 's1', text: 'Does your AI or data system include — or have a clear roadmap to include — support for African languages beyond English and major colonial languages?', hint: 'Think: Yoruba, Swahili, Hausa, Amharic, Kinyarwanda, Igbo, Zulu, etc. Even one is a start.' },
    { id: 's2', text: 'Does your solution process data at the edge (locally, on device or community server) rather than requiring cloud round-trips for core functionality?', hint: 'Think: on-device inference, local databases, edge compute nodes.' },
    { id: 's3', text: 'Are there explicit ethical guidelines — fairness, accountability, transparency — built into how AI makes or supports decisions in your solution?', hint: 'Think: bias audits, explainability, community review of AI outputs, human-in-the-loop for high stakes decisions.' },
    { id: 's4', text: 'Does your solution support voice or audio interfaces as a primary — not just an optional — interaction mode?', hint: 'Think: oral cultures, low literacy contexts, hands-free operation, local language speech recognition.' },
    { id: 's5', text: 'Is the AI or data system in your solution transparent and understandable to the communities using it — not a black box?', hint: 'Think: can a community health worker explain why the AI said what it said? Can users contest or override outputs?' }
  ],
  social: [
    { id: 'o1', text: 'Does the community your solution serves have clear ownership or governance rights over the data they generate through your system?', hint: 'Think: community data trusts, local storage, consent mechanisms, deletion rights, collective ownership structures.' },
    { id: 'o2', text: 'Was your target community involved in co-designing or defining the requirements — not just as users, but as co-authors of the solution?', hint: 'Think: participatory design, community scoping, co-creation workshops, local researcher involvement.' },
    { id: 'o3', text: 'Does your solution work within or alongside informal economic systems — not requiring bank accounts, formal ID, or registered business status?', hint: 'Think: mobile money, cash compatible, shared device use, community voucher systems, informal credit recognition.' },
    { id: 'o4', text: 'Does your solution respect and actively integrate existing cultural protocols, knowledge systems, and community governance structures?', hint: 'Think: elder approval, gender-appropriate access, sacred/restricted knowledge categories, traditional decision-making rhythms.' },
    { id: 'o5', text: 'Does your solution benefit the collective — a community, cooperative, or group — not just individual users in isolation?', hint: 'Think: shared insights, community dashboards, collective benefit flows, group governance of outputs.' }
  ],
  principles: [
    { id: 'pr1', text: 'Does your solution center networks of relationships — not just individual user accounts — as the primary unit of design?', hint: 'Principle: Relationality Over Individualism. Ubuntu: I am because we are.' },
    { id: 'pr2', text: 'Does data generated by and about the community stay sovereign to that community — not extracted to external platforms for their benefit?', hint: 'Principle: Sovereignty Over Extraction. Who profits from the data? Where do insights go first?' },
    { id: 'pr3', text: 'Is your solution designed for longevity, repairability, and environmental appropriateness — rather than planned obsolescence and rapid replacement cycles?', hint: 'Principle: Sustainability Over Scale. Can it run for 5 years without a hardware upgrade?' },
    { id: 'pr4', text: 'Does your solution adapt meaningfully to different local languages, cultural contexts, and geographic conditions — rather than deploying a single global standard?', hint: 'Principle: Diversity Over Uniformity. One solution deployed everywhere fails everywhere eventually.' },
    { id: 'pr5', text: 'Does your solution integrate with and strengthen what already exists — rather than displacing existing knowledge, trust networks, or economic systems?', hint: 'Principle: Integration Over Disruption. What does the community already have that you can amplify?' }
  ]
};

const GAP_ADVICE: Record<string, string> = {
  p1: 'Design episodic computing into your architecture — queue tasks when power is available, pause gracefully when it is not.',
  p2: 'Implement an offline-first data strategy: local SQLite or PouchDB, with selective sync when connectivity is detected.',
  p3: 'Set a hardware floor — test on a 2GB RAM device with Android 8.',
  p4: 'Consult open-hardware principles. Support devices with repair ecosystems.',
  p5: 'Audit every API call. Use binary protocols, aggressive caching, and image compression.',
  s1: 'Partner with Masakhane for African language models. Integrate Mozilla Common Voice datasets.',
  s2: 'Evaluate TensorFlow Lite or ONNX Runtime for on-device inference.',
  s3: 'Implement a community AI review process. Document model limitations.',
  s4: 'Prioritize voice UI from day one. Use Mozilla Common Voice or Whisper for STT.',
  s5: 'Implement explainability layers — confidence scores, key factors, simple language summaries.',
  o1: 'Draft a Community Data Trust agreement. Store data locally first.',
  o2: 'Run at least one co-design sprint with community members before your next build cycle.',
  o3: 'Remove the bank account requirement. Accept mobile money. Design for shared device use.',
  o4: 'Conduct a cultural protocol audit with community elders.',
  o5: 'Build community-level dashboards and insights. Route value to collective governance structures first.',
  pr1: 'Redesign your user model. Replace "user account" with "community node".',
  pr2: 'Audit where your data flows. Implement local-first storage.',
  pr3: 'Set a 5-year device lifecycle target. Choose components with a repair ecosystem.',
  pr4: 'Build localisation as a core feature. Create a local adaptation toolkit.',
  pr5: 'Map existing systems before building. Design your solution to slot in, not replace.'
};

const STEPS = [
  { id: 'intro', label: '1 · Intro', layerName: null },
  { id: 'physical', label: '2 · Physical', layerName: 'physical' },
  { id: 'spatial', label: '3 · Spatial', layerName: 'spatial' },
  { id: 'social', label: '4 · Social', layerName: 'social' },
  { id: 'principles', label: '5 · Principles', layerName: 'principles' },
  { id: 'results', label: '6 · Results', layerName: null }
];

export default function SPSSChecker() {
  const [currentStep, setCurrentStep] = useState(0);
  const [scores, setScores] = useState<Record<string, number>>({});
  const [ideaInfo, setIdeaInfo] = useState({ name: '', sector: '', desc: '' });
  const [errorName, setErrorName] = useState(false);

  const handleNext = () => {
    if (currentStep === 0) {
      if (!ideaInfo.name.trim()) {
        setErrorName(true);
        return;
      }
      setErrorName(false);
    }
    
    if (currentStep >= 1 && currentStep <= 4) {
      const layer = STEPS[currentStep].layerName;
      if (layer) {
        const questions = QUESTIONS[layer as keyof typeof QUESTIONS];
        const allAnswered = questions.every(q => scores[q.id] !== undefined);
        if (!allAnswered) {
          alert("Please answer all questions before continuing.");
          return;
        }
      }
    }
    
    setCurrentStep(Math.min(currentStep + 1, STEPS.length - 1));
  };

  const handleBack = () => setCurrentStep(Math.max(currentStep - 1, 0));
  
  const handleScore = (qId: string, score: number) => {
    setScores(prev => ({ ...prev, [qId]: score }));
  };

  const getLayerScore = (layer: string) => {
    return QUESTIONS[layer as keyof typeof QUESTIONS].reduce((sum, q) => sum + (scores[q.id] || 0), 0);
  };

  const renderResults = () => {
    const physScore = getLayerScore('physical');
    const spatScore = getLayerScore('spatial');
    const socScore = getLayerScore('social');
    const priScore = getLayerScore('principles');
    const total = physScore + spatScore + socScore + priScore;
    const pct = Math.round((total / 200) * 100);

    let level, levelDesc;
    if (pct >= 86) {
      level = 'SPSS Exemplar';
      levelDesc = 'This solution embodies the SPSS framework. It is built from communities, for communities, with genuine attention to all three layers and core principles. Share it — it is a model.';
    } else if (pct >= 71) {
      level = 'SPSS Aligned';
      levelDesc = 'Strong SPSS alignment. This solution is on the right path. Address the identified gaps to move toward exemplar status — the foundation is solid.';
    } else if (pct >= 51) {
      level = 'SPSS Informed';
      levelDesc = 'This solution shows SPSS awareness but has meaningful gaps. The framework thinking is present — now it needs to be operationalized in the weaker layers.';
    } else if (pct >= 31) {
      level = 'SPSS Orientation Needed';
      levelDesc = 'There are early signals of SPSS thinking, but significant gaps exist across multiple layers. This solution needs intentional redesign before it can serve the communities it targets.';
    } else {
      level = 'SPSS Misaligned';
      levelDesc = 'This solution currently operates from standard technology assumptions that the SPSS framework specifically inverts. Foundational redesign is needed.';
    }

    const gaps: {id: string, text: string, advice: string}[] = [];
    const strengths: string[] = [];
    
    Object.keys(QUESTIONS).forEach(layer => {
      QUESTIONS[layer as keyof typeof QUESTIONS].forEach(q => {
        if (scores[q.id] === 0) gaps.push({ id: q.id, text: q.text, advice: GAP_ADVICE[q.id] });
        else if (scores[q.id] === 10) strengths.push(q.text.split('—')[0].trim());
      });
    });

    return (
      <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
        <div className="text-center mb-12">
          <div className="inline-block bg-surface border border-border shadow-sm rounded-2xl px-12 py-8">
            <div className="font-display text-5xl font-bold text-obsidian tracking-tighter">{pct}%</div>
            <div className="font-sans text-xl font-semibold text-obsidian mt-2 mb-1">{level}</div>
            <div className="font-mono text-xs text-subtle uppercase tracking-wider">{ideaInfo.name} {ideaInfo.sector ? `· ${ideaInfo.sector}` : ''}</div>
          </div>
          <p className="max-w-xl mx-auto mt-6 text-sm text-subtle leading-relaxed">
            {levelDesc}
          </p>
        </div>

        <div className="bg-surface border border-border p-8 rounded-xl mb-8 shadow-sm">
          <h3 className="font-display text-lg font-semibold text-obsidian mb-6">Score by Layer</h3>
          {[
            { label: 'Physical Layer', score: physScore },
            { label: 'Spatial Layer', score: spatScore },
            { label: 'Social Layer', score: socScore },
            { label: 'Core Principles', score: priScore }
          ].map((l, i) => (
            <div key={i} className="mb-4">
              <div className="flex justify-between items-center mb-1.5">
                <span className="font-medium text-xs uppercase tracking-wide text-obsidian">{l.label}</span>
                <span className="font-mono text-xs text-subtle">{l.score} / 50</span>
              </div>
              <div className="h-2 w-full bg-canvas rounded-full overflow-hidden">
                <div 
                  className="h-full bg-obsidian transition-all duration-1000 ease-out rounded-full" 
                  style={{ width: `${(l.score / 50) * 100}%` }}
                />
              </div>
            </div>
          ))}
        </div>

        {strengths.length > 0 && (
          <div className="mb-8">
            <h3 className="font-display text-base font-semibold text-obsidian mb-4 flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-surface border border-obsidian text-obsidian flex items-center justify-center text-xs">✓</span>
              What's Working
            </h3>
            <div className="space-y-2">
              {strengths.slice(0, 5).map((s, i) => (
                <div key={i} className="bg-surface border border-border/60 py-3 px-4 rounded-md text-sm text-subtle shadow-sm border-l-2 border-l-obsidian">
                  {s}
                </div>
              ))}
            </div>
          </div>
        )}

        {gaps.length > 0 && (
          <div className="mb-8">
            <h3 className="font-display text-base font-semibold text-obsidian mb-4 flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-canvas border border-border text-subtle flex items-center justify-center text-xs">!</span>
              Critical Gaps & Remedies
            </h3>
            <div className="space-y-3">
              {gaps.slice(0, 6).map((g, i) => (
                <div key={i} className="bg-canvas border border-border py-4 px-5 rounded-md shadow-sm">
                  <strong className="block text-sm text-obsidian mb-1.5 font-medium">{g.text.split('?')[0]}?</strong>
                  <span className="text-sm text-subtle block pl-3 border-l px-2 border-border/80">→ {g.advice}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        <div className="bg-surface border border-border p-8 rounded-xl shadow-sm text-center">
          <h3 className="font-display text-lg font-semibold text-obsidian mb-3">Your SPSS Next Steps</h3>
          <p className="text-sm text-subtle mb-6">Take these actionable steps based on your gap analysis.</p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button 
              onClick={() => {
                setCurrentStep(0);
                setScores({});
                setIdeaInfo({ name: '', sector: '', desc: '' });
              }}
              className="px-6 py-2.5 bg-canvas border border-border text-obsidian text-sm font-medium rounded hover:bg-surface hover:shadow-sm transition-all"
            >
              Start Over
            </button>
            <a 
              href="#"
              className="px-6 py-2.5 bg-obsidian text-white text-sm font-medium rounded hover:shadow-md transition-all flex items-center justify-center gap-2"
            >
              Share Report
              <ArrowRight className="w-4 h-4" />
            </a>
          </div>
        </div>
      </div>
    );
  };

  return (
    <section id="checker" className="py-32 px-6 md:px-12 lg:px-20 border-t border-border/60 bg-canvas">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-surface border border-border/60 shadow-sm mb-6">
            <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse"></span>
            <span className="font-mono text-[10px] font-medium text-obsidian uppercase tracking-wider">
              Interactive Tool
            </span>
          </div>
          <h2 className="font-display text-3xl md:text-4xl font-semibold text-obsidian tracking-tight mb-4">
            SPSS Compliance Checker
          </h2>
          <p className="text-subtle text-base max-w-2xl mx-auto leading-relaxed">
            Run your idea, product, or initiative against the SPSS framework. Get a layer-by-layer score, gap analysis, and concrete recommendations — in under 3 minutes.
          </p>
        </div>

        <div className="relative">
          {/* Progress Indication */}
          <div className="flex flex-wrap justify-center gap-2 mb-10">
            {STEPS.map((s, i) => (
              <div 
                key={s.id} 
                className={`px-4 py-1.5 rounded-full text-xs font-medium border transition-all duration-300 ${
                  i === currentStep 
                    ? 'bg-obsidian border-obsidian text-white shadow-md scale-105'
                    : i < currentStep 
                      ? 'bg-surface border-border text-obsidian shadow-sm'
                      : 'bg-transparent border-border/50 text-subtle/50'
                }`}
              >
                {s.label}
              </div>
            ))}
          </div>

          <div className="w-full h-1.5 bg-border/40 rounded-full mb-12 overflow-hidden">
            <div 
              className="h-full bg-obsidian transition-all duration-500 ease-out rounded-full"
              style={{ width: `${(currentStep / (STEPS.length - 1)) * 100}%` }}
            />
          </div>

          {/* Form Content */}
          <div className="min-h-[400px]">
            {currentStep === 0 && (
              <div className="bg-surface border border-border p-8 md:p-12 rounded-xl shadow-sm animate-in fade-in slide-in-from-bottom-4 duration-500">
                <h3 className="font-display text-2xl font-semibold text-obsidian mb-3">Tell us about your idea</h3>
                <p className="text-sm text-subtle mb-8">This tool evaluates your solution against the three SPSS layers and five core principles. Partial credit is real credit.</p>
                
                <div className="space-y-6">
                  <div>
                    <label className="block text-sm font-medium text-obsidian mb-2">What is your idea or solution called?</label>
                    <input 
                      type="text" 
                      value={ideaInfo.name}
                      onChange={e => setIdeaInfo(prev => ({...prev, name: e.target.value}))}
                      placeholder="e.g. AgriVoice AI, Community Kiosk..."
                      className={`w-full px-4 py-3 bg-canvas border ${errorName ? 'border-red-500 ring-1 ring-red-500' : 'border-border'} rounded focus:outline-none focus:border-obsidian transition-colors text-obsidian`}
                    />
                    {errorName && <p className="text-xs text-red-500 mt-1">Please provide a name to continue.</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-obsidian mb-2">Which sector does it primarily serve?</label>
                    <select 
                      value={ideaInfo.sector}
                      onChange={e => setIdeaInfo(prev => ({...prev, sector: e.target.value}))}
                      className="w-full px-4 py-3 bg-canvas border border-border rounded focus:outline-none focus:border-obsidian transition-colors text-obsidian appearance-none"
                    >
                      <option value="">Select a sector...</option>
                      <option value="Agriculture">Agriculture</option>
                      <option value="Health">Health</option>
                      <option value="Education">Education</option>
                      <option value="Finance">Finance / Fintech</option>
                      <option value="Governance">Governance / Civic Tech</option>
                      <option value="Other">Other</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-obsidian mb-2">Briefly describe what it does <span className="text-subtle font-normal">(optional)</span></label>
                    <textarea 
                      value={ideaInfo.desc}
                      onChange={e => setIdeaInfo(prev => ({...prev, desc: e.target.value}))}
                      placeholder="A 1-2 sentence summary..."
                      rows={3}
                      className="w-full px-4 py-3 bg-canvas border border-border rounded focus:outline-none focus:border-obsidian transition-colors text-obsidian resize-none"
                    />
                  </div>
                </div>
              </div>
            )}

            {currentStep >= 1 && currentStep <= 4 && (
              <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
                <div className="mb-8 border-l-4 border-obsidian pl-6">
                  <h3 className="font-display text-2xl font-semibold text-obsidian">{STEPS[currentStep].label.split('· ')[1]} Layer</h3>
                  <p className="text-sm text-subtle mt-1">Answer honestly to locate actual gaps in your architecture.</p>
                </div>
                
                <div className="space-y-6">
                  {QUESTIONS[STEPS[currentStep].layerName as keyof typeof QUESTIONS].map((q, i) => (
                    <div 
                      key={q.id} 
                      className={`bg-surface border p-6 rounded-xl transition-all duration-300 ${scores[q.id] !== undefined ? 'border-obsidian/30 shadow-sm' : 'border-border'}`}
                    >
                      <p className="text-obsidian font-medium mb-2 pr-6">
                        <span className="text-subtle mr-2">{i + 1}.</span>{q.text}
                      </p>
                      <p className="text-xs text-subtle italic mb-6">💡 {q.hint}</p>
                      
                      <div className="flex flex-wrap gap-3">
                        {[
                          { val: 0, label: '✗ No', class: 'hover:border-red-500 hover:text-red-600', sel: 'border-red-500 bg-red-50 text-red-700' },
                          { val: 5, label: '◑ Partially', class: 'hover:border-amber-500 hover:text-amber-600', sel: 'border-amber-500 bg-amber-50 text-amber-700' },
                          { val: 10, label: '✓ Yes', class: 'hover:border-green-500 hover:text-green-600', sel: 'border-green-500 bg-green-50 text-green-700' }
                        ].map(opt => (
                          <button
                            key={opt.val}
                            onClick={() => handleScore(q.id, opt.val)}
                            className={`flex-1 min-w-[100px] py-2.5 px-4 rounded border text-sm font-medium transition-all duration-200 ${
                              scores[q.id] === opt.val 
                                ? opt.sel 
                                : `border-border bg-canvas text-subtle ${opt.class}`
                            }`}
                          >
                            {opt.label}
                          </button>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {currentStep === 5 && renderResults()}
          </div>

          {/* Navigation Controls */}
          {currentStep < 5 && (
            <div className="flex justify-between items-center mt-12 pt-8 border-t border-border/60">
              {currentStep > 0 ? (
                <button 
                  onClick={handleBack}
                  className="px-6 py-2.5 text-sm font-medium text-subtle hover:text-obsidian flex items-center gap-2 transition-colors"
                >
                  <ArrowLeft className="w-4 h-4" />
                  Back
                </button>
              ) : <div></div>}
              
              <button 
                onClick={handleNext}
                className="px-8 py-3 bg-obsidian text-white text-sm font-medium rounded hover:shadow-lg hover:-translate-y-0.5 transition-all flex items-center gap-2 group"
              >
                {currentStep === 4 ? 'See My Results' : 'Continue'}
                <ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1" />
              </button>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
